### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by WeiChihChern** [netw0rkf10w/CRF#3]
Hi, thanks for the great work.

I tried to install the pack via the `python3 setup.py install`, however as I `import CRF` I got no module name 'CRF'. 

Do you have any insight regarding this? Thanks.

Here's what CRF-0.0.01-py3.6-linux-x86_64.egg directory has in my machine:
![image](https://user-images.githubusercontent.com/40074617/156821917-0753ace1-d480-4eba-b90e-8c7867b480cd.png)

**Comment by Ending2015a** [comment]
Hello, @WeiChihChern 
Could you share how did you resolve this issue?
I'm also facing this issue. Thank you.

**Comment by netw0rkf10w** [comment]
@Ending2015a Sorry this is indeed an issue. @WeiChihChern closed the issue so quickly that I thought there was no issue and thus I didn't look into it.

I'm working on a fix now, please stay tuned.

**Comment by netw0rkf10w** [comment]
This has been fixed. Please pull the repo and re-install the package again.

Something like the following commands should work:

```bash
pip uninstall CRF
cd CRF
git pull origin main
python setup.py install
```

**Comment by netw0rkf10w** [comment]
@Ending2015a Please let me know if the fix worked for you. Thanks.

**Comment by Ending2015a** [comment]
> @Ending2015a Please let me know if the fix worked for you. Thanks.

Hello @netw0rkf10w thank you for fixing this importing issue. Now it works perfect on cuda! :+1:
