### ISSUE TITLE
 can you post your version of pytorch 、cuda and cudnn,that maybe useful to test.Thanks!

### ISSUE THREAD

**Issue by 18972441546** [netw0rkf10w/CRF#5]

**Comment by netw0rkf10w** [comment]
Thanks for the feedback. It should work for **PyTorch >= 1.6, CUDA >= 10.1, and cuDNN >= 7.6**. I have updated the [Installation](https://github.com/netw0rkf10w/CRF#installation) section of the README to add this information.

Please let me know if you have any issues or any further questions.

**Comment by 18972441546** [comment]
Dear Blogger of netw0rkf10w :
&nbsp; &nbsp; &nbsp; &nbsp; I am grateful for your help!But I meet a problem.You can see the attachment if it is convenient for you.
Yours sincerely, Yours faithfully,


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netw0rkf10w/CRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netw0rkf10w/CRF]  can you post your version of pytorch 、cuda and cudnn,that maybe useful to test.Thanks! (Issue #5)





 
Thanks for the feedback. It should work for PyTorch &gt;= 1.6, CUDA &gt;= 10.1, and cuDNN &gt;= 7.6. I have updated the Installation section of the README to add this information.
 
Please let me know if you have any issues or any further questions.
